from .BaseLoss import BaseLoss
from .SoftmaxLoss import SoftmaxLoss
from .CosineSimilarityLoss import CosineSimilarityLoss
from .DenoisingAutoEncoderLoss import DenoisingAutoEncoderLoss
from .MultipleNegativesRankingLoss import MultipleNegativesRankingLoss
